name: CI Testing

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      -
      - uses: php-actions/phpunit@v9
        with:
          version: '8.0'
        #   php_extensions: xdebug
        #   configuration: phpunit.xml
        #   args: --coverage-text
        # env:
        #   XDEBUG_MODE: coverage
